spring:
  datasource:
    url: jdbc:h2:mem:studydb
    username: sa
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    defer-database-initialization: true

jwt:
  issuer: dgsw@gmail.com
  secret_key: c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0
  access_expiration_minutes: 15 # 액세스 토큰 만료(분)
  refresh_expiration_days: 14 # 리프레시 토큰 만료(일)

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs

  default-consumes-media-type: application/json
  auto-tag-classes: true
  groups:
    enabled: false

  swagger-ui:
    tags-sorter: alpha
    operationsSorter: alpha
    path: /swagger-ui/index.html